---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jraverdyorange/yml-tools 
    tag: latest

inputs:
  - name: mysql-boshrelease-ci
  - name: prometheus-version
  - name: shield-version

outputs:
  - name: bosh-version-ops
  - name: output
  
run:
  path: mysql-boshrelease-ci/scripts/check-version-ops.sh