---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: cf-mysql-release
  - name: cf-mysql-deployment 
  - name: mysql-boshrelease-ci

outputs:
  - name: version-release-mysql
  - name: output
  
run:
  path: mysql-boshrelease-ci/scripts/check-version-mysql.sh