---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: mysql-boshrelease-ci

outputs:
  - name: bosh-director-config

run:
  path: mysql-boshrelease-ci/scripts/create-bosh-config.sh