---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: cf-mysql-release
  - name: cf-mysql-deployment
  - name: mysql-boshrelease-ci
  - name: bosh-director-config

run:
  path: mysql-boshrelease-ci/scripts/deploy-mysql-release.sh