---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: cf-mysql-release
  - name: cf-mysql-deployment
  - name: mysql-boshrelease-ci

outputs:
  - name: deployment-manifest

run:
  path: mysql-boshrelease-ci/scripts/interpolate-manifest.sh

params:
  OUTPUT_FILE: deployment-manifest/deployment.yml
  DEPLOYMENT_NAME : ((bosh-deployment.name))
  ARBITRATOR:       ((bosh-deployment.arbitrator))
  SYSLOG:           ((bosh-deployment.syslog))
  PROMETHEUS:       ((bosh-deployment.prometheus))
  SHIELD:           ((bosh-deployment.shield))
  TYPE_OS:         "ubuntu-trusty"