---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
- name: cf-mysql-release
- name: cf-mysql-deployment
- name: mysql-boshrelease-ci

outputs:
- name: deployment-manifest

run:
  path: mysql-boshrelease-ci/scripts/interpolate-manifest

params:
  OUTPUT_FILE: deployment-manifest/deployment.yml
  ENABLE_INTERRUPTOR: false
  MINIMAL_MODE: false
  NO_ARBITRATOR: false
  ENABLE_REMOTE_ADMIN_ACCESS: false
  SET_CF_MYSQL_HOST: false
