---
- path: /name
  type: replace
  value: "cf-mysql-concourse"

- type: replace
  path: /stemcells/os=ubuntu-trusty  
  value:
    alias: default
    os: ((type_os))
    version: latest

### vm mysql
- path: /instance_groups/name=mysql/networks
  type: replace
  value: [{name: mysql-net}]

- path: /instance_groups/name=mysql/azs
  type: replace
  value: [z1]

- path: /instance_groups/name=mysql/vm_type
  type: replace
  value: "small"

### vm proxy
- path: /instance_groups/name=proxy/networks
  type: replace
  value: [{name: mysql-net}]

- path: /instance_groups/name=proxy/azs
  type: replace
  value: [z1]

- path: /instance_groups/name=proxy/vm_type
  type: replace
  value: "small"  

### errand
- path: /instance_groups/name=bootstrap-vm/networks
  type: replace
  value: [{name: mysql-net}]

- path: /instance_groups/name=bootstrap-vm/vm_type
  type: replace
  value: "small"    


- path: /instance_groups/name=rejoin-unsafe-vm/networks
  type: replace
  value: [{name: mysql-net}]

- path: /instance_groups/name=rejoin-unsafe-vm/vm_type
  type: replace
  value: "small"    


- path: /instance_groups/name=verify-cluster-schemas-vm/networks
  type: replace
  value: [{name: mysql-net}]

- path: /instance_groups/name=verify-cluster-schemas-vm/vm_type
  type: replace
  value: "small"    

  
- path: /instance_groups/name=smoke-tests-vm/networks
  type: replace
  value: [{name: mysql-net}]

- path: /instance_groups/name=smoke-tests-vm/vm_type
  type: replace
  value: "small"    

- type: replace
  path: /releases/name=bpm?
  value:
    name: bpm
    version: "0.9.0"
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.9.0
    sha1: 0cb3242063c95271c95b62de3a6d07072aff0b29