#!/usr/bin/env bash 

set -eux

: "${MINIMAL_MODE:=false}"
: "${NO_ARBITRATOR:=false}"
: "${ENABLE_REMOTE_ADMIN_ACCESS:=false}"
: "${VARS_FILE:=}"

VARS_FILE_OPTION=''
if [[ ! -z "${VARS_FILE}" ]]; then
  VARS_FILE_OPTION="-l ${VARS_FILE}"
fi

operations=""
variables=""

if ${MINIMAL_MODE}; then
    operations="$operations -o ./mysql-boshrelease-ci/operations/minimal-mode.yml"
fi

if ${NO_ARBITRATOR}; then
    operations="$operations -o ./cf-mysql-deployment/operations/no-arbitrator.yml"
fi

if ${ENABLE_REMOTE_ADMIN_ACCESS}; then
    operations="$operations -o ./mysql-boshrelease-ci/operations/enable-remote-admin-access.yml"
fi

OUTPUT_FILE_DIR=$(dirname "${OUTPUT_FILE}")

cd $HOME

bosh interpolate \
    ./cf-mysql-deployment/cf-mysql-deployment.yml \
    -o ./cf-mysql-deployment/operations/latest-versions.yml \
    ${operations} \
    ${VARS_FILE_OPTION} \
    ${variables} \
    -l ./cf-mysql-deployment/bosh-lite/default-vars.yml \
    -o ./mysql-boshrelease-ci/operations/customize.yml \
    --vars-store ./mysql-boshrelease-ci/operations/credentials.yml \
    > ./manifest-with-variables.yml

#bosh interpolate \
#    ./manifest-with-variables.yml \
#    -o ./cf-mysql-ci/operations/remove-variables.yml \
##    > "${OUTPUT_FILE}"